#!/bin/bash

echo "replaceing $1 to $2"
rg $1 --files-with-matches | xargs sed -i '' "-e s/$1/$2/g"
echo "done :-)"

# seenReplace=''
# 
# for arg in "$@"; do
#   if test "$arg" == '--replace' -o "$arg" == '-r'; then
#     seenReplace='true'
#     break
#   fi
# done
# 
# if test -z "$seenReplace"; then
#   echo 'You must specify the --replace or -r argument!'
#   exit 1
# fi
# 
# currentFile=''
# didChange=''
# 
# (
#   rg \
#     --files-with-matches \
#     "$@"
#   echo -e '\n\0'
# ) |
# {
#   while IFS= read -r -d '' part; do
#     if test -n "$currentFile"; then
#       echo "$currentFile"
#       head -n -2 <<< "$part" > "$currentFile"
#       didChange='true'
#     fi
#     currentFile="$(tail -n 1 <<< "$part")"
#   done
# 
#   if test -z "$didChange"; then
#     echo "No files were changed."
#     exit 1
#   fi
# }
